---
- name: Setup Longhorn storage
  ansible.builtin.include_tasks: ../../tasks/longhorn_disk_setup.yml

- name: Download K3s install script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s-install.sh
    mode: '0755'

- name: Join worker to cluster
  ansible.builtin.command:
    cmd: /tmp/k3s-install.sh
  environment:
    K3S_TOKEN: "{{ global_k3s_token }}"
    INSTALL_K3S_EXEC: >-
      agent
      --server https://{{ vip_address }}:6443
      --flannel-iface {{ flannel_iface }}
      --node-ip {{ ansible_host }}
      --node-label node.longhorn.io/create-default-disk=true
  changed_when: true

- name: Label worker node
  delegate_to: localhost
  become: false
  kubernetes.core.k8s:
    kind: Node
    name: "{{ inventory_hostname }}"
    definition:
      metadata:
        labels:
          node-role.kubernetes.io/worker: "true"
