---
- name: Setup Longhorn storage
  ansible.builtin.include_tasks: ../../tasks/longhorn_setup.yml

- name: Download K3s install script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s-install.sh
    mode: '0755'

- name: Join Master to Cluster
  ansible.builtin.command:
    cmd: /tmp/k3s-install.sh
  environment:
    K3S_TOKEN: "{{ global_k3s_token }}"
    INSTALL_K3S_EXEC: >-
      server
      --server https://{{ vip_address }}:6443
      --tls-san {{ vip_address }}
      --flannel-iface {{ flannel_iface }}
      --node-ip {{ ansible_host }}
      --disable traefik
      --disable servicelb
  changed_when: true
