---
ansible_user: debian
ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
k3s_manifests_directory: /var/lib/rancher/k3s/server/manifests

flannel_iface: eth1
vip_address: '10.9.9.99'
vip_service_cidrs: '10.9.9.90/32,10.9.8.90/32'

argocd_repo_url: "https://github.com/Starktastic-Homelab/platform.git"
