---
- name: Setup Longhorn storage
  ansible.builtin.include_tasks: ../../tasks/longhorn_setup.yml

- name: Download K3s install script
  ansible.builtin.get_url:
    url: https://get.k3s.io
    dest: /tmp/k3s-install.sh
    mode: '0755'

- name: Install K3s (Init)
  ansible.builtin.command:
    cmd: /tmp/k3s-install.sh
  environment:
    INSTALL_K3S_EXEC: >-
      server
      --cluster-init
      --tls-san {{ vip_address }}
      --flannel-iface {{ flannel_iface }}
      --node-ip {{ ansible_host }}
      --disable traefik
      --disable servicelb
  changed_when: true

- name: Set up Kube-Vip
  ansible.builtin.include_tasks: kube-vip.yml

- name: Setup local kubeconfig
  ansible.builtin.include_tasks: kubeconfig.yml
