name: Deploy K3s Cluster

on:
  workflow_dispatch:

  repository_dispatch:
    types: [infrastructure-changed]

  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'renovate.json'

jobs:
  deploy:
    name: Apply Configuration
    runs-on: self-hosted
    container:
      image: ansible/ansible:default
    env:
      PROXMOX_URL: ${{ secrets.PROXMOX_URL }}
      PROXMOX_USER: ${{ secrets.PROXMOX_USER }}
      PROXMOX_TOKEN_ID: ${{ secrets.PROXMOX_TOKEN_ID }}
      PROXMOX_TOKEN_SECRET: ${{ secrets.PROXMOX_TOKEN_SECRET }}

    steps:
      - uses: actions/checkout@v6

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Setup Helm
        uses: azure/setup-helm@v4.3.1
        with:
          version: 'v3.19.2'

      - name: Install Helm Diff Plugin
        run: |
          if ! helm plugin list | grep -q "diff"; then
            helm plugin install https://github.com/databus23/helm-diff
          else
            echo "Helm diff plugin already installed. Skipping."
          fi

      - name: Setup SSH Key
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 400 private_key.pem

      - name: Create Ansible Vault password file
        run: echo "${{ secrets.ANSIBLE_VAULT_PASSWORD }}" > .vault_pass

      - name: Run K3s Playbook
        run: |
          ansible-playbook -i inventory/proxmox.yml \
            --vault-password-file .vault_pass \
            --private-key private_key.pem \
            k3s.yml
