---
name: Check Ansible syntax and dry run
on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

jobs:
  validate:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Run ansible-lint
        uses: ansible/ansible-lint@v25.9.2

  dry-run:
    name: Ansible Dry Run
    runs-on: self-hosted
    needs: validate
    steps:
      - uses: actions/checkout@v5

      - uses: MrStarktastic/setup-python@v1.1
        with:
          python-version: '3.x'
          pip-install: 'ansible'
          cache: 'pip'

      - name: Run Ansible Playbook in check mode
        run: |
          ansible-playbook -i inventory/proxmox.yml k3s.yml --check
